### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ghost** [zechaos031/Bot-Discord-Structure#8]
ted identifier
compile (internal/modules/cjs/loader.js:811:22)←[39m
odule._extensions..js (internal/modules/cjs/loader.js:879:10)←[39m
oad (internal/modules/cjs/loader.js:731:32)←[39m
.Module._load (internal/modules/cjs/loader.js:644:12)←[39m
.Module.runMain (internal/modules/cjs/loader.js:931:10)←[39m
/main/run_main_module.js:17:11←[39m
launched !
dPromiseRejectionWarning: Error: Shard 0's process exited before its Client became ready.
ous> (C:\Users\ryan\node_modules\discord.js\src\sharding\Shard.js:88:39)
apper (events.js:291:20)
vents.js:203:13)
Exit (C:\Users\ryan\node_modules\discord.js\src\sharding\Shard.js:272:10)
emit (events.js:203:13)
Process._handle.onexit (internal/child_process.js:272:12)
dPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 77)
p\MY BOTS\Bot-Discord-Structures\main.js:5
ents:[
^^^^

**Comment by JusteLoneWolf** [comment]
Have you create database/guilddb folder ?

**Comment by JusteLoneWolf** [comment]
And normally we have another error at the top of the console

**Comment by JusteLoneWolf** [comment]
I close this issue because I have no respond since 1 month
